.env
.gitignore
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/payjp.js
app/assets/stylesheets/card.scss
app/controllers/card_controller.rb
app/controllers/productions_controller.rb
app/controllers/users/registrations_controller.rb
app/helpers/card_helper.rb
app/models/card.rb
app/models/customer.rb
app/models/user.rb
app/views/card/new.html.haml
app/views/card/show.html.haml
app/views/layouts/application.html.haml
app/views/productions/_header.html.haml
config/routes.rb
db/migrate/20200806115926_create_productions.rb
db/migrate/20200807080513_create_cards.rb
db/migrate/20200807085729_create_customers.rb
db/schema.rb
test/controllers/card_controller_test.rb
test/fixtures/cards.yml
test/fixtures/customers.yml
test/models/card_test.rb
test/models/customer_test.rb

他のメンバーがjsファイルを使いたいとの事で
まずは、カードのcreateまではできているのですが
その後、カードの詳細ページへの繊維だけができていないので、そこまでの確認お願いいたします。
クレジットカードの遷移前のマイページなどの作成も終わっていないので
ここまでで、他のメンバーの協力して進めていきたいと思ってます。

[WIP]クレジットカードcreateまで

---

app/assets/stylesheets/_mypage.scss
app/assets/stylesheets/_side.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/views/productions/_header.html.haml
app/views/users/_side.html.haml
app/views/users/show.html.haml
config/routes.rb
db/schema.rb
test/controllers/users_controller_test.rb

##What
　必須マークアップのmypage
##Why
フリマアプリ機能に必要な為
※ログアウト、カード編集、商品ページ、プロフィール画像等は未実装

[WIP]mypageマークアップ

---

app/assets/stylesheets/_btn.scss
app/assets/stylesheets/_header.scss
app/assets/stylesheets/_midle.scss
app/views/productions/_btn.html.haml
app/views/productions/_header.html.haml
app/views/productions/_list.html.haml
app/views/productions/index.html.haml

##what
カテゴリー機能実装
##why
アプリケーション必須機能なため
カテゴリーにみ実装
残り商品一覧機能実装でトップページ終了

[WIP]トップカテゴリー実装

---

.env
.gitignore
Gemfile
Gemfile.lock
app/controllers/card_controller.rb
app/models/address.rb
app/models/card.rb
app/models/user.rb
config/initializers/devise.rb
config/routes.rb

修正　validates　.env 消した

---

app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.haml
app/views/productions/_header.html.haml
db/migrate/20200806023829_devise_create_users.rb
db/schema.rb

ユーザー登録　誕生日登録できるまで

---

app/assets/stylesheets/new.scss
app/views/productions/_btn.html.haml
app/views/productions/new.html.haml
app/views/users/_side.html.haml
config/routes.rb

商品投稿ページのマークアップ実装
アプリケーションに必要な機能である商品投稿ページののマークアップを実装しました。
https://i.gyazo.com/b19ab161fe789ff10dc928cbec3f9171.mp4

商品投稿機能画面実装

---

app/assets/stylesheets/_show.scss
app/views/productions/_list.html.haml
app/views/productions/show.html.haml
config/routes.rb

　商品詳細ページ
　アプリ実装で必要な機能だから
https://gyazo.com/bd9bd46a001e6fb36d8a6d28e42a1add

商品詳細ページ遷移　マークアップ

---

.gitignore
app/assets/javascripts/application.js
app/javascript/packs/application.js
app/javascript/payjp.js
app/views/cards/new.html.haml
app/views/layouts/application.html.haml
config/webpack/environment.js
package.json
yarn.lock

それぞれが
環境変数を定義して呼び出せるようにした
jsファイルはpackの方を使う

クレカ、環境変数での呼び出し

---

app/javascript/category.js
app/javascript/payjp.js
config/routes.rb

##what
クレジットカードの登録と削除の動作確認。
出品機能の動作確認
##why
進捗の確認のため

動作確認/クレカ系、出品系

---

app/assets/stylesheets/_cardshow.scss
app/assets/stylesheets/product_new.scss
app/controllers/productions_controller.rb
app/views/cards/show.html.haml

カード削除マークアップ

---

app/views/devise/registrations/new.html.haml
app/views/devise/registrations/new_address.html.haml
spec/models/user_spec.rb

ユーザーのテストコード
アプリのクオリティ向上のため
https://i.gyazo.com/78a8ba0f6779c356eb8ce3443385c65c.jpg

ユーザーテストコード

---

app/assets/stylesheets/_flash.scss
app/assets/stylesheets/purchase.scss
app/views/purchase/index.html.haml

Flash 購入が完了しました

---

app/assets/stylesheets/_show.scss
app/controllers/productions_controller.rb
app/views/productions/show.html.haml
db/migrate/20200806115926_create_productions.rb
db/schema.rb

＃WHAT
　詳細ページの情報の表示のみ
　
＃WHY
　メンバーが他の機能の実装にて使うため。
　情報の表示のみを実装。

[WIP]詳細ページ表示

---

app/assets/stylesheets/_show.scss

詳細ページボタン修正

---

app/assets/stylesheets/_show.scss
app/assets/stylesheets/likes.scss
app/controllers/likes_controller.rb
app/controllers/users_controller.rb
app/helpers/likes_helper.rb
app/models/like.rb
app/models/production.rb
app/models/user.rb
app/views/likes/_like.html.haml
app/views/likes/create.js.erb
app/views/likes/destroy.js.erb
app/views/productions/show.html.haml
app/views/users/_side.html.haml
app/views/users/index.html.haml
config/breadcrumbs.rb
config/routes.rb
db/migrate/20200824092404_create_likes.rb
db/schema.rb
spec/factories/likes.rb
spec/helpers/likes_helper_spec.rb
spec/models/like_spec.rb
spec/requests/likes_request_spec.rb

＃what
お気に入り機能の実装
＃why
ユーザーが気になった出品物を確認するため。

お気に入り機能　修正

---

README.md

readme test1

---

README.md

readme写真導入test

---

README.md

test logo1

---

README.md

readme 写真finder

---

README.md

readme　写真２

---

README.md

readmeの中身にて、それぞれの実装の内容を簡単に記述しております

readme チーム開発実装内容簡潔な物
